### ISSUE TITLE
Input and Output Module

### ISSUE THREAD

**Issue by kjeverson** [dsu-arl/pace-python-dojo#3]
- Printing Text
    - [x] Description
    - [x] Challenge
    - [x] Verify Script
- Variables
    - [x] Description
    - [x] Challenge
    - [x] Verify Script
- Format Printing
    - [x] Description
    - [x] Challenge
    - [x] Verify Script
- User Input
    - [x] Description
    - [x] Challenge
    - [x] Verify Script
- Type Casting
    - [x] Description
    - [x] Challenge
    - [x] Verify Script

**Comment by cford23** [comment]
Challenge gives error message "Error: Make sure that you are printing 'Hello, Name'!" when run with the following code:
```python
name = 'Connor'
print('Hello, {}'.format(name))
```

Currently only passes if `name = 'greg'`
