### ISSUE TITLE
Conditionals Module

### ISSUE THREAD

**Issue by kjeverson** [dsu-arl/pace-python-dojo#5]
- If Statements
    - [x] Description
    - [x] Challenge
    - [x] Verify Script
- If-Else Statements
    - [x] Description
    - [x] Challenge
    - [x] Verify Script
- Nested Conditionals
    - [x] Description
    - [x] Challenge
    - [x] Verify Script
- Else-If Blocks
    - [x] Description
    - [x] Challenge
    - [x] Verify Script
- Logical Operators
    - [x] Description
    - [x] Challenge
    - [x] Verify Scripts

**Comment by d4rkr41n** [comment]
Verify scripts added, need to test them to make sure they work now.
