### ISSUE TITLE
Loops Module

### ISSUE THREAD

**Issue by kjeverson** [dsu-arl/pace-python-dojo#6]
- While Loops
    - [x] Description
    - [x] Challenge
    - [x] Verify Script
- Python Lists
    - [x] Description
    - [x] Challenge
    - [x] Verify Script
- Range Function
    - [x] Description
    - [x] Challenge
    - [x] Verify Script
- For Loops
    - [x] Description
    - [x] Challenge
    - [x] Verify Script

**Comment by d4rkr41n** [comment]
these bois ready to be tested
